name: Build APK and Release Artifacts

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Specify the Java distribution

    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleGoogleAlpha

    - name: Upload APKs as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: APKs
        path: |
          app/build/outputs/apk/google/alpha/*/*.apk
          app/build/outputs/apk/google/alpha/*/*/*.apk

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          This is the release for build ${{ github.run_number }}.
        draft: false
        prerelease: false
