name: Build APK

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: gradle
  
    - name: List files in the directory
      run: ls -l
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
  
    - name: Build with Gradle
      run: ./gradlew assembleGoogleAlpha

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
          name: APKs
          path: |
            app/build/outputs/apk/google/alpha/*/*.apk
            app/build/outputs/apk/google/alpha/*/*/*.apk

    - name: Upload Current SHA as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: last-sha
        path: last_sha.txt

    - name: Delete Old Pre-Releases
      id: delete-pre-releases
      uses: sgpublic/delete-release-action@master
      with:
        pre-release-drop: true
        pre-release-keep-count: 3
        pre-release-drop-tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
